
package card;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cardcrudl", targetNamespace = "http://card/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    card.ObjectFactory.class
})
public interface Cardcrudl {


    /**
     * 
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://card/Cardcrudl/deleteRequest", output = "http://card/Cardcrudl/deleteResponse")
    public String delete(
        @WebParam(name = "cardNumber", partName = "cardNumber")
        int cardNumber);

    /**
     * 
     * @return
     *     returns card.ListCards
     */
    @WebMethod(operationName = "Display")
    @WebResult(partName = "return")
    @Action(input = "http://card/Cardcrudl/DisplayRequest", output = "http://card/Cardcrudl/DisplayResponse")
    public card.ListCards display();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://card/Cardcrudl/cardcrudlRequest", output = "http://card/Cardcrudl/cardcrudlResponse")
    public void cardcrudl();

}
